name: Terraform Validate & Format

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Validate Terraform in all "day*" folders
    runs-on: ubuntu-latest

     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Setup AWS Credentials
        run: |
          cat > dummy.tfvars << EOF
          access_key = "dummy"
          secret_key = "dummy"
          EOF

      - name: Validate each Terraform project in folders starting with "day"
        run: |
          for dir in $(find . -type f -name 'main.tf' -path './day*/*' -exec dirname {} \; | sort -u); do
            echo "ðŸ” Validating Terraform in $dir"
            # Copy dummy credentials to each directory
            cp dummy.tfvars "$dir/terraform.tfvars"
            
            # Initialize and validate
            cd "$dir"
            rm -rf .terraform .terraform.lock.hcl
            terraform init -backend=false
            terraform validate
            cd - > /dev/null
          done

